package common;

public enum PageType {
	// student
	STUDENT_DASHBOARD_PAGE,
	PDT_DASHBOARD_PAGE,
	PDT_MANAGERSV_PAGE,
	PDT_MANAGERGV_PAGE,
	PDT_CHIANHOM_PAGE,
	PDT_DSACHNHOM_PAGE,
	PDT_SVCHUADANGKY_PAGE,
	PDT_SVDADANGKY_PAGE,
	PDT_CHITIETNHOM_PAGE,
	PDT_DOTDK_PAGE,
	
	CNBM_DASHBOARD_PAGE,
	CNBM_MANAGERSV_PAGE,
	CNBM_MANAGERGV_PAGE,
	CNBM_CHIANHOM_PAGE,
	CNBM_DSACHNHOM_PAGE,
	CNBM_SVCHUADANGKY_PAGE,
	CNBM_SVDADANGKY_PAGE,
	CNBM_CHITIETNHOM_PAGE,
	
	admin_DASHBOARD_PAGE,
	admin_MANAGERSV_PAGE,
	admin_MANAGERGV_PAGE,
	admin_CHIANHOM_PAGE,
	admin_DSACHNHOM_PAGE,
	admin_SVCHUADANGKY_PAGE,
	admin_SVDADANGKY_PAGE,
	admin_CHITIETNHOM_PAGE,
	admin_MANAGER_NV_PAGE,
	chitietGV,
	admin_hocky,
	admin_dotdangky,
	
	GIANGVIEN_PAGE,
	LOGIN,

	STAFF,
	


}